version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333
      # Add other env vars as needed
    depends_on:
      - redis
      - qdrant
    volumes:
      - .:/usr/src/app
    command: npm run dev

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: rag-worker
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - redis
      - qdrant
    volumes:
      - .:/usr/src/app
    command: npm run worker

  redis:
    image: redis:7-alpine
    container_name: rag-redis
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
